# start by pulling the python image
FROM python:3.10

EXPOSE 5000

# copy the requirements file into the image
COPY src/requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY src /app
COPY wsgi.ini .

# configure the container to run in an executed manner
ENTRYPOINT [ "uwsgi", "wsgi.ini" ]